### ISSUE TITLE
Footer overlaps page content at the bottom

### ISSUE THREAD

**Issue by maennenajere** [movie-explorer/website#33]
When scrolling to the bottom of the page, the footer overlaps the main content and hides other elements. This makes interacting with the page hard and affects the user experience.
![Screenshot 2024-11-18 215719](https://github.com/user-attachments/assets/62306431-6e77-4b76-8238-45e25c7e2a68)

**Comment by maennenajere** [comment]
what is status of this?

**Comment by santeripas** [comment]
> what is status of this?

it is solved
